services:

  # ==============================
  # PostgreSQL
  # ==============================
  postgres:
    image: postgres:16
    container_name: postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: kogo
      POSTGRES_PASSWORD: math1106

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

  # ==============================
  # React Build
  # ==============================
  frontend:
    build:
      context: ./frontend

    container_name: frontend

    volumes:
      - react-dist:/dist

    command: >
      sh -c "
      npm ci &&
      npm run build &&
      rm -rf /dist/* &&
      cp -r dist/. /dist
      "

  # ==============================
  # Django Backend
  # ==============================
  backend:
    build:
      context: ./backend

    container_name: backend

    restart: unless-stopped

    depends_on:
      - postgres

    environment:
      DB_NAME: mydb
      DB_USER: kogo
      DB_PASSWORD: math1106
      DB_HOST: postgres
      DB_PORT: 5432

    ports:
      - "8000:8000"

    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000
      "

  # ==============================
  # Nginx
  # ==============================
  nginx:
    build:
      context: ./nginx

    container_name: nginx

    restart: unless-stopped

    depends_on:
      - backend
      - frontend

    ports:
      - "80:80"

    volumes:
      - react-dist:/usr/share/nginx/html

volumes:
  postgres-data:
  react-dist: